# Generated by Django 4.2.7 on 2023-12-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0003_alter_user_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorites',
        ),
    ]
