# Generated by Django 4.2.7 on 2023-12-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_app', '0008_alter_contact_email_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='contact_app.contact'),
        ),
    ]
